import Footer from "@/@modules/@common/layouts/footer";
import StateProvider from "@/providers/state-provider";
import type { Metadata } from "next";
import "swiper/css";
import "swiper/css/navigation";
import "./globals.css";
import "@/styles/main.scss";
import { UserProvider } from "@/@modules/context/user-context";
import NewsletterModal from "@/@modules/modal";
import Header from "@/@modules/@common/layouts/header";
import MobileBottomNav from "@/@modules/@common/button-bottom";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body>
        <StateProvider>
          <UserProvider>
            <Header />
            {children}
                <NewsletterModal ttlDays={1} />
                <MobileBottomNav />
            <Footer />
          </UserProvider>
        </StateProvider>
      </body>
    </html>
  );
}
